# Generated by Django 2.0.6 on 2019-05-31 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adopcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('', 'Selecciona un sexo'), ('M', 'Macho'), ('H', 'Hembra')], default=None, max_length=10)),
                ('aproximated_ege', models.IntegerField()),
                ('rescue_date', models.DateField()),
                ('persons', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcion.Person')),
            ],
        ),
    ]
